SIMULATION_TIMESTEPS := 100
EPS := 2.2204e-15

INPUT_DIR_RAW := ../examples/example3
INPUT_DIR := \"$(INPUT_DIR_RAW)\"
OUTPUT_DIR := \"$(INPUT_DIR_RAW)/out\"
REFERENCE_DIR := \"$(INPUT_DIR_RAW)/reference\"

INPUT_VECTORS := x0 w
INPUT_MATRICES := a b invh g s f

WRITE_FORMAT := \"%.4le\"

DEFINES := TEST_CASES SIMULATION_TIMESTEPS EPS N_DIM M_DIM HORIZON C_DIM INPUT_DIR OUTPUT_DIR WRITE_FORMAT REFERENCE_DIR
